name: Publish

env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
          registry-url: https://npm.pkg.github.com/
          scope: '@wisersolutions'
      - uses: actions/checkout@master
      - run: npm i --frozen-lockfile
      - run: npm run build
      - run: npm publish
